shell_arch_packages:
  - zsh

shell_aur_packages:
  - oh-my-posh
  - zsh-antidote

shell_homebrew_packages:
  - antidote
  - eza
  - fd
  - fzf
  - oh-my-posh
  - zsh

shell_zsh_path: "{{ '/bin/zsh' if is_macos else '/usr/bin/zsh' }}"
