default_linemode devicons
set preview_images true 
set preview_images_method kitty
# set preview_images_method ueberzug
set viewmode!
set column_ratios 2,3,5
set hidden_filter ^\.|\.(?:pyc|pyo|bak|swp)$|^lost\+found$|^__(py)?cache__$
set show_hidden false
set confirm_on_delete multiple
set vcs_aware true 
set unicode_ellipsis true
map <C-p> fzf_select
map <C-t> tab_new
unmap <C-n>
map <C-l> toggle_flat
map F console scout -ftsea%space
#map <C-g> fzf_locatej
# set draw_borders both
unmap x
unmap a
map a console touch_mkdir_p%space
map x quitall
unmap <C-b>
map <C-b> open_with_browser
