oci_docker_enabled: true
oci_docker_compose_enabled: true
oci_docker_service_enabled: false
oci_minikube_enabled: false

oci_arch_packages:
  - docker

oci_arch_compose_packages:
  - docker-compose

oci_podman_arch_packages:
  - podman

oci_podman_homebrew_packages:
  - podman

# TODO: Revisit whether minikube is the right smallest K8s footprint or whether
# kind/k3s would fit better once the container workflow is clearer.
