- name: Install Python development packages on Arch
  become: true
  community.general.pacman:
    name: "{{ python_dev_arch_packages }}"
    state: present
  when: is_archlinux | bool

- name: Install Python development packages on macOS
  community.general.homebrew:
    name: "{{ python_dev_homebrew_packages }}"
    state: present
  when: is_macos | bool

- name: Install global Python development packages on Arch
  ansible.builtin.pip:
    name: "{{ python_dev_global_packages }}"
    extra_args: --user --break-system-packages
    executable: "{{ pip3_executable }}"
  when: is_archlinux | bool

- name: Install global Python development packages on macOS
  ansible.builtin.pip:
    name: "{{ python_dev_global_packages }}"
    extra_args: --user
    executable: "{{ pip3_executable }}"
  when: is_macos | bool

- name: Install Poetry on Arch when requested
  become: true
  community.general.pacman:
    name: "{{ python_dev_poetry_arch_packages }}"
    state: present
  when:
    - is_archlinux | bool
    - python_dev_poetry_enabled | bool

- name: Install Poetry on macOS when requested
  community.general.homebrew:
    name: "{{ python_dev_poetry_homebrew_packages }}"
    state: present
  when:
    - is_macos | bool
    - python_dev_poetry_enabled | bool
