return {
	"oncomouse/lushwal.nvim",
	cmd = { "LushwalCompile" },
	dependencies = {
		{ "rktjmp/lush.nvim" },
		{ "rktjmp/shipwright.nvim" },
	},
	lazy = false,
	config = function()
		vim.g.lushwal_configuration = {
			transparent_background = true,
			compile_to_vimscript = true,
			terminal_colors = false,
			color_overrides = nil,
			-- wal_path = vim.fn.expand("XDG_CACHE_HOME/wal/colors.json"),
			addons = {
				ale = false,
				barbar = false,
				bufferline_nvim = true,
				coc_nvim = false,
				dashboard_nvim = false,
				fern_vim = false,
				gina = false,
				gitsigns_nvim = true,
				hop_nvim = false,
				hydra_nvim = false,
				indent_blankline_nvim = false,
				lightspeed_nvim = false,
				lspsaga_nvim = false,
				lsp_trouble_nvim = true,
				lualine = true,
				markdown = true,
				mini_nvim = true,
				native_lsp = true,
				neogit = true,
				neomake = false,
				nerdtree = true,
				nvim_cmp = true,
				nvim_tree_lua = true,
				nvim_ts_rainbow = false,
				semshi = false,
				telescope_nvim = true,
				treesitter = true,
				vim_dirvish = false,
				vim_gitgutter = true,
				vim_signify = false,
				vim_sneak = false,
				which_key_nvim = false,
			},
		}
	end,
}
