# Really need to consider getting a bold font for things like field name in yaml
include ~/.cache/wal/colors-kitty.conf
background_opacity 1
dynamic_background_opacity yes
font_size 12.0
enable_audio_bell no
bell_border_color     #83816e
symbol_map U+1F600-U+1F6FF emoji OpenMoji Color


allow_remote_control yes

hide_window_decorations yes
cursor_trail 3
cursor_trail_decay 0.1 0.3

map ctrl+shift+t none

# map f1 set_background_opacity --toggle 0.8
# map f1 kitten set-background-opacity --toggle 0.8
map f1 remote_control set-background-opacity --toggle 0.7
map f2 remote_control set-background-opacity --toggle 0


## BEGIN_KITTY_FONTS
## font_features YourMainFont +calt +liga +dlig
#font_family      family="FiraCode Nerd Font"
#bold_font        auto
#italic_font      auto
#bold_italic_font auto
## END_KITTY_FONTS
# bold_font        auto
# italic_font      auto
# bold_italic_font auto



adjust_line_height 0
adjust_column_width 0
box_drawing_scale 0.001, 1, 1.5, 2
# Enable proper emoji/icon rendering
symbol_map U+1F000-U+1F77F Noto Color Emoji
narrow_symbols U+E000-U+F8FF 1
narrow_symbols U+1F300-U+1F5FF 2
# Fix width for special characters
modify_font cell_width 100%
modify_font baseline 0

# Force Kitty to use the full cell for drawing
box_drawing_scale 0.001, 1, 1.5, 2
# ====================================
# pipe to url scan
map f3 pipe @ansi window less +G -R
# pipe to vim
# copy paste : shortcuts amd buffer
# fonts and overwrites
# history browsing
# set env
cursor     #E95678
cursor_shape     block
# cursor_blink_interval     3
scrollback_lines 5000
wheel_scroll_multiplier 5.0
url_color #26BBD9
url_style curly
open_url_modifiers ctrl+shift
open_url_with $BROWSER
# copy_on_select yes
rectangle_select_modifiers ctrl+alt
# select_by_word_characters :@-./_~?&=%+#
mouse_hide_wait 1.0
window_border_width 0
window_margin_width 0
window_padding_width 0
# map ctrl+shift+u        input_unicode_character
# map ctrl+shift+e        run_simple_kitten text url_hints
map ctrl+shift+alt+t    set_tab_title
map ctrl+shift+v        paste_from_clipboard
map ctrl+shift+s        paste_from_selection
map ctrl+shift+c        copy_to_clipboard
# map ctrl+shift+o        pass_selection_to_program
# map ctrl+shift+up        scroll_line_up
# map ctrl+shift+down      scroll_line_down
# map ctrl+shift+k         scroll_line_up
# map ctrl+shift+j         scroll_line_down
# map ctrl+shift+page_up   scroll_page_up
# map ctrl+shift+page_down scroll_page_down
# map ctrl+shift+home      scroll_home
# map ctrl+shift+end       scroll_end
# map ctrl+shift+h         show_scrollback
# close_on_child_death no
# term xterm-256color
# map kitty_mod+f9 clear_terminal reset active
map kitty_mod+f10 clear_terminal clear active
map kitty_mod+f11 clear_terminal scrollback active
map kitty_mod+f12 clear_terminal scroll active
# scrollback_pager less +G -R
scrollback_pager nvim -c 'set ft=man' -
window_border_width 0
window_margin_width 0
window_padding_width 0
single_window_margin_width 0
placement_strategy top-left
hide_window_decorations yes
cell_height_scale 1.0
cell_width_scale 1.0
adjust_line_height 0
adjust_column_width 0


# font_family      JetBrainsMono Nerd Font Mono 
font_family      FiraCode Nerd Font Mono
italic_font family="Monaspace Radon NF"
italic_font family="VictorMono Nerd Font"
bold_font family="Monaspace Krypton NF"
# bold_italic_font JetBrainsMono Nerd Font Mono Bold Italic
# italic_font  family="CaskaydiaCove Nerd Font"
bold_font  family="CaskaydiaCove Nerd Font"
