- name: Install base R packages
  ansible.builtin.import_tasks: packages.yml

- name: Configure R runtime
  ansible.builtin.import_tasks: config.yml

- name: Install default R libraries
  ansible.builtin.import_tasks: libraries.yml

- name: Install radian tooling
  ansible.builtin.import_tasks: radian.yml
  when: r_lang_radian_enabled | bool
