script=/usr/lib/mpv-mpris/mpris.so
video-aspect-override=no
keepaspect=yes
keepaspectratio=yes
keepaspect-window=yes

# -----------
# sub-font='Arial Regular'
osd-font=FiraCode Nerd Font
sub-font=FiraCode Nerd Font
sub-border-size=1
sub-color='#CDCDCD'
# sub-shadow=3
sub-shadow-color='#000000'
# sub-shadow-offset=2
# -----------

# Window scaling mode (only allow diagonal resizing)
window-scale-mode=downscale-big
wayland-title="${filename}"
wayland-app-id=jelly-mpv
