source = ~/.config/hypr/hypridle.d/*.conf

general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = hyprlock # loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 180
    on-timeout = ~/.local/bin/hypridle-power-state.sh dpms-off-if-not-discharging
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = ~/.local/bin/hypridle-power-state.sh lock-if-discharging
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800
    on-timeout = ~/.local/bin/hypridle-power-state.sh lock-if-not-discharging
    on-resume = hyprctl dispatch dpms on
}
