windowrule = match:class obsidian, workspace special:obsi silent
exec-once = obsidian --no-sandbox --ozone-platform=wayland --ozone-platform-hint=auto --enable-features=UseOzonePlatform,WaylandWindowDecorations
