- import_playbook: main.yml
  vars:
    dotfiles_profile: hyprland
    identity_enabled: true
    appearance_enabled: true
    shell_enabled: true
    tty_enabled: true
    python_dev_enabled: true
    ecmascript_enabled: true
    golang_enabled: true
    tower_enabled: true
    linux_desktop_enabled: true
    hyprland_enabled: true
    system_tty_login_enabled: true
    browser_base_enabled: true
    browser_personal_enabled: true
    browser_bitwarden_enabled: true
    media_enabled: true
    nvim_enabled: true
    pkm_enabled: true
    pim_enabled: true
    email_enabled: true
    r_lang_enabled: true
    java_enabled: false
    share_sync_enabled: true
    llm_enabled: true
    llm_opencode_enabled: true
    llm_claudecode_enabled: false
    tty_dv_enabled: true
    tty_gh_enabled: true
    tty_glab_enabled: true
    tty_newsboat_enabled: true
    tty_neofetch_enabled: true
    tty_pywal_enabled: true
    appearance_generate_wallpapers: true
    appearance_install_colorwhirl_target: true
    appearance_install_matugen: true
